version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_SERVER=${VITE_BACKEND_SERVER}
      env_file:
        - .env
    ports:
      - "${FRONTEND_PORT}:8080"
    networks:
      - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      env_file:
        - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DB_CONNECTION=${DB_CONNECTION}
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
