version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_SERVER=${VITE_BACKEND_SERVER}
    ports:
      - 4000:4000
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
    networks:
      - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DB_CONNECTION=${DB_CONNECTION}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

