version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000 
