services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    volumes:
      - './data:/data/db'
  frontend:
    image: wodosharlatan/quick_note:frontend
    ports:
      - 4000:4000
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
  backend:
    image: wodosharlatan/quick_note:backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DB_CONNECTION=${DB_CONNECTION}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}